name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install packaging dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential libssl-dev g++
          sudo gem install --no-document fpm

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build shared library
        run: |
          cd cpp
          g++ -std=c++20 -O2 -fPIC -shared -Iexternal/json/single_include reznjcs.cpp -o libreznjcs_amd64.so
          cp libreznjcs_amd64.so ../dist/

      - name: Build and create .deb package
        run: |
          make ARCH=amd64 RAW_VERSION=${{ github.ref_name }}
          cp build/reznjcs-cli dist/
          cp *.deb dist/

      - name: Make binaries executable
        run: chmod +x dist/reznjcs-cli

      - name: Create tarball of CLI binary
        run: tar -czvf dist/rezn-jcs_amd64.tar.gz -C dist reznjcs-cli

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.deb
            dist/libreznjcs_amd64.so
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}